### ISSUE TITLE
Update system

### ISSUE THREAD

**Issue by farribeiro** [feross/webtorrent-desktop#1010]
A update system for the program using the webtorrent protocol. Downloading by site and github is very slow. Identify the plaform and OS. Very effective for MSI(windows) packages and portable

**Comment by feross** [comment]
We're going to solve the download slowness by using a CDN instead of relying on GitHub. See https://github.com/feross/webtorrent-www/issues/108

As for using the webtorrent protocol to update the app, that's a really cool idea! Unfortunately, I'm afraid that updating a desktop app in place, while it's running is not an easy problem. You have to ensure that the code signature for the app remains intact, as well as platform differences. It's not an easy problem.

I'd prefer to continue relying on the battle tested Squirrel updater included in Electron.
