### ISSUE TITLE
VLC player issues in 0.17.1 on Mac

### ISSUE THREAD

**Issue by ethaniel** [feross/webtorrent-desktop#1044]
When I open the clip from WebTorrent and switch to VLC, the http stream gets added to the playlist but doesn't start. I have to find the file by hand and open it in VLC myself.

Here is a
[VLC.txt.txt](https://github.com/feross/webtorrent-desktop/files/530539/VLC.txt.txt)
 log from VLC.

**Comment by feross** [comment]
VLC's http streaming is a bit janky and has several outstanding bugs that the developers refuse to fix. From your logs, it looks like you may have triggered such a scenario. Does this happen with all video files, or just some? I've noticed that certain file encodings cause the VLC http streamer to fail completely.

One other thing to check: make sure you're on the latest version of WebTorrent Desktop (0.17.2) because there was a bug where VLC streams would fail to start that was fixed recently.
