### ISSUE TITLE
VLC menu is not accessable

### ISSUE THREAD

**Issue by aurimus** [feross/webtorrent-desktop#1069]
Expect: VLC menu to be integrated in the unity

Actual: Menu is not present, the only option is right clicking the video (which actually is also sloppy)

0.17.2
Ubuntu 16.10

**Comment by feross** [comment]
Are you using WebTorrent to stream to VLC? Are you suggesting that your normal OS menu that shows for each app isn't showing for VLC? This is probably because the window is sized to take up your whole screen and we launch VLC with the `float-on-top` option enabled.

Sorry, we can't change this option as it's the only way to get VLC to take focus when it's launched.

**Comment by aurimus** [comment]
@feross , I made a video of how it looks like and explained everything:
https://drive.google.com/file/d/0B6hpw3kYc6qXTXBOSVJSdzd1UFU/view

I use Popcorn Time every now and then and it launches VLC without problem. The `float-on-top` has nothing to do with it probably as it's just "Always on top" (popcorn doesn't have that but it focuses still - same OS, same VLC0

**Comment by feross** [comment]
I'm really sorry but I can't help you if you're using WebTorrent for copyright infringement. It's our project policy that we close issues like that.
