### ISSUE TITLE
Error: ENAMETOOLONG: name too long, unlink

### ISSUE THREAD

**Issue by theSoenke** [feross/webtorrent-desktop#1074]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
v0.17.2

**What operating system and version?**
Solus

**What did you do?**
Package webtorrent-desktop

**What did you expect to happen?**
Build electron package

**What actually happened?**
When running npm run package -- linux it creates recursively directories until it fails with the error Error: ENAMETOOLONG: name too long, unlink

Building it directly with electron packager works without problems: electron-packager . --platform=linux --arch=x64

**Comment by feross** [comment]
I've never heard of the OS you're using before: [Solus](https://solus-project.com/). I would love for you to be able to build the app on Solus, but I don't have a copy lying around to test with. You also might be our only Solus user.

It would help if you could add `console.log` calls to the `package.js` script and figure out which ine is causing the issue for you. It also might help to update your version of Node.js to the latest version of 6.x, which is currently 6.9.4. 

If you figure out what the cause is, we are happy to accept a pull request to fix the issue.
