### ISSUE TITLE
Use/Allow STUN

### ISSUE THREAD

**Issue by DiegoRBaquero** [feross/webtorrent-desktop#1115]
We should add a default STUN server or allow users to specify one

**Comment by feross** [comment]
There is a default STUN server, but it's offline because Mozilla shut it down. See: https://github.com/feross/simple-peer/issues/120

We should publish a new version of WebTorrent Desktop to fix the issue you reported on Twitter. https://twitter.com/DiegoRBaquero/status/826911478959714304

@DiegoRBaquero Once this is fixed, do you think there's still a need to let the user specify a custom server?

**Comment by DiegoRBaquero** [comment]
I think Google's STUN should be enough.

WD isn't using any STUN atm: https://github.com/feross/webtorrent-desktop/blob/852fc86cbd69cef20d51c82d5d5cfbebd4aa93bf/src/renderer/webtorrent.js#L65

I only said to allow custom because non is specified atm.

**Comment by DiegoRBaquero** [comment]
Oh, nevermind, I didn't know simple-peer used a default (Google's atm) STUN server by default if non specified.

All we need to do is build a new version. For webtorrent.io website, the PR in instant.io which exposes the custom rtcConfig needs to be merged.

**Comment by feross** [comment]
Yep, merged the instant.io PR now. I also changed the code to just use Twilio's STUN server (which is returned in the response, but we were filtering and replacing with Mozilla's/Google's). This is simpler.

Sounds good -- so new WebTorrent Desktop release should completely resolve this issue.

**Comment by DiegoRBaquero** [comment]
Great! 

webtorrent main lib should be up to date as it was built 8 days ago with Google's STUN server which was merged 17 days ago.
