### ISSUE TITLE
OS X: Mouseover not captured on invisible player header

### ISSUE THREAD

**Issue by feross** [feross/webtorrent-desktop#241]

**Comment by demoneaux** [comment]
Not too sure what this issue is about. Any elaborations?

**Comment by mathiasvr** [comment]
The header div does not trigger the mouseover event. If you move the cursor down into the player window the mouseover event is first triggered when the cursor is below the header rather than when entering the window. You can try opening the player and wait for the header and controls to become invisible, then move the cursor into the player from above. The correct behavior should be as when you move the cursor in from below or any of the sides.
