### ISSUE TITLE
Add torrent expand/delete animations

### ISSUE THREAD

**Issue by feross** [feross/webtorrent-desktop#255]

**Comment by dcposch** [comment]
Just tried this and it feels really slow and choppy, even tho I have a four core i7.

I think that's because of CPU contention. Eventually we probably want WebTorrent to run in it's own process / hidden window, separate from the main window.

Currently we're not making good use of people's cores, because the CPU intensive torrent work is single threaded on the UI thread.

**Comment by dcposch** [comment]
Let's reopen this once we fix that?

**Comment by feross** [comment]
Not important
