### ISSUE TITLE
Ubuntu "package is of bad quality"

### ISSUE THREAD

**Issue by dcposch** [feross/webtorrent-desktop#326]
```
Lintian check results for /home/dc/Downloads/webtorrent-desktop_0.3.1-1_amd64.deb:
E: webtorrent-desktop: control-file-has-bad-permissions postinst 1363 != 0755
E: webtorrent-desktop: control-file-has-bad-permissions postrm 1363 != 0755
```

![image](https://cloud.githubusercontent.com/assets/169280/14316701/5c4b09f8-fbb9-11e5-89d7-319776ca6b5e.png)

**Comment by dcposch** [comment]
@grunjol i know what file mode 755 is, but what is file mode 1363?? i thought the highest was 777 (aka full permissions for everyone)

**Comment by dcposch** [comment]
After clicking past the warning, it doesn't install:

![image](https://cloud.githubusercontent.com/assets/169280/14316807/e44c8070-fbb9-11e5-9e52-81dbe8cd68c2.png)

**Comment by grunjol** [comment]
preinst and postinst are defined 0755 in package builder

about symlink, are updating a previous installation?

**Comment by grunjol** [comment]
done, tested in ubuntu 15.10 and debian 8

**Comment by grunjol** [comment]
btw, the problem was originated when `standard` complained about 0755 was not a valid number (because of the leading 0), to avoid that, i quoted the number, but then it was casted to octal again by `tar-stream`  because the parameter was interpreted as octal string, instead of decimal, in that case 
0755 (decimal) === 1363 (octal) and the invalid mode.
