### ISSUE TITLE
Feature Suggestion : Video.js 

### ISSUE THREAD

**Issue by wallydz** [feross/webtorrent-desktop#345]
The actual player is really basic, maybe using video.js will externalize the part of player and give you more time for the core 

Cheers !

**Comment by feross** [comment]
Thanks for the suggestion. We'll take a look.

**Comment by mmcc** [comment]
@feross Feel free to ping me if you're ever interested in trying it out. It'd be super cool to see VJS used :)

**Comment by feross** [comment]
@mmcc Will do! I think what we have right now is working pretty well. Do you know what new features or improvements we'd gain by switching?

**Comment by mmcc** [comment]
@feross It's honestly probably one of those "not broke don't fix" kinda deals for you, but theoretically you would get better support for things like WebVTT captions. Beyond that, things like custom styling could be nice for you, along with easily being able to add plugins long term. 

It's a little hard for me to say what the biggest benefit would be since the Electron App use case is a little out of our usual wheel house. Selfishly, that's one reason I'm interested in seeing you try it out :)

**Comment by feross** [comment]
We already have support for WebVTT and our styling is already pretty nice, I think. 👍 But if we were doing it from scratch, I'd give it a try. Maybe a future project?

**Comment by mmcc** [comment]
Didn't mean to imply the current styling isn't already nice (it is!), meant more from the end user's perspective.

Sounds good!

**Comment by feross** [comment]
@mmcc Yep! I didn't take what you said to be negative :)
