### ISSUE TITLE
Tray icon does not show if libappindicator1 is not installed

### ISSUE THREAD

**Issue by feross** [feross/webtorrent-desktop#383]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu) `master` and `v0.3.3`

**What operating system and version?** Ubuntu 15.10

**What did you do?** Launch the app. Close the main window.

**What did you expect to happen?** Tray icon should be visible to indicate that the app is still running.

**What actually happened?** No tray icon.

I think we should just get rid of the tray icon on Linux systems until the Electron Tray API is more reliable. These issues don't exist on Windows, as far as I'm aware.

@dcposch @grunjol Thoughts?

**Comment by feross** [comment]
Looks like this happens if `libappindicator1` is not installed.

@grunjol Can we add that a dependency to the .deb file?

**Comment by feross** [comment]
Also, if there is some way to detect if `libappindicator1` is installed, we should do that (for users who use the .zip version) and use the old behavior for them (i.e. quit the app instead of minimize to tray).

**Comment by grunjol** [comment]
`libappindicator1` is ubuntu specific (unity) so other debian derivates won't have them in the repository, we can not enforce them (we can suggest).

The problem is how to handle other DEs, because you can have other trays (like the one used by `i3`)  that is not `libappindicator1` based, and electron uses.

Also, we can not detect loaded libraries in memory from node code without an electron API. We can check the existence of a file, but again, the location of the libraries is very distro/version dependent, so the only solution is what electron does, try to load the dynamic library (ie: `libappindicator1`) and if it fails, try another tray library. That is what isSupported() method should expose.

Until they expose the API we can:

* Close the program on close handler (revert to old behavior) 
* Minimize to taskbar/launcher and keep the _shutdown_ option (this is what  i saw in some versions of `amule`)

Also, we can still use the tray to have a constant desktop indicator, if the system supports it you can call it from there, if not, the program is still in minimized state and user can bring focus on it.

**Comment by dcposch** [comment]
I'll add more detailed OS tracking in the update check. I wonder how many of our users use Ubuntu vs other Linux distributions.

I would be down to support minimize-to-tray on Ubuntu only. On any other Linux distro, WebTorrent would still work, but it would quit once you close the window.

> Also, if there is some way to detect if libappindicator1 is installed, we should do that and use the old behavior for them 

This sounds good to me. Most people on Ubuntu will already have it installed -- it looks like Chrome also requires it.

**Comment by grunjol** [comment]
Correction: `libappindicator1` is in debian since `wheezy` (2013), we can enforce it in dependencies to make sure user has it.
