### ISSUE TITLE
Remember video position

### ISSUE THREAD

**Issue by sguergachi** [feross/webtorrent-desktop#405]
Would be great if playing video and pressing the back button, then playing the video would resume at the last position instead of starting the video from the start.

**Comment by dcposch** [comment]
OTOH it might be confusing / feel flaky if you press play on a video that you first watched a year ago and it jumps directly to the end credits

**Comment by dcposch** [comment]
**Trying something new: let's have a vote**

If you want want WebTorrent to remember your position in each video, upvote here >>

**Comment by dcposch** [comment]
If you want WebTorrent play videos from the start each time, upvote here ^^

**Comment by sguergachi** [comment]
One way to do it is if you started a vid, and then come back to it it shows a dialog asking if you want to continue or restart. That's how Plex handles

**Comment by Johnius** [comment]
@dcposch I have couple of arguments why we should save last position:
1. More often you would like to continue watching video
2. It is easier to start from the beginning than remember and seek for last position—is is like a book mark.

And couple why we shouldn't show dialog with Continue and Restart as VLC does:
1. It will block UI and user will need to point mouse and make a click on one of the buttons. Even more user must think what to do—useless cognitive tension.
2. If you want to start watching from the beginning—lets add a button Go To Beginning. We will still have a click but only on demand, not necessary.

Am I right?

**Comment by sguergachi** [comment]
Yes, I agree. It should resume, preferably with no intermediate UI. I'm wondering what the opposing reason for saving position?

**Comment by dcposch** [comment]
Haha OK, looks like I'm outvoted. I'll try to add it.

> I'm wondering what the opposing reason for saving position?

There's some complexity. We just have to make sure we handle all the corner cases gracefully
* If someone plays a video to the end, and then they exit while the credits are rolling, we don't want to jump back to the end when they reopen the video.
* If we ever implement autoplay, for example to automatically continue from one chapter to the next in an audiobook torrent, it will require special handling. You never want to jump from the end of eg Chapter 6 to the middle of Chapter 7.

**Comment by grunjol** [comment]
The solution might be some kind of indicator of the position in the home screen. Maybe a pie-like overlay on the play button? or in case of multiple files besides the file list, but its not always displayed...

**Comment by dispix** [comment]
Hi, pretty new here but i guess I can add my 2 cents on this issue. I personally really hate when I open a video I previously watched but closed during the credits and it opens on the credits again. A lot of people will close the video at ~ 99% of playtime because credits start rolling and if you remember that position I think lots of people will find it annoying to click on a reset button to start playing their torrent again.

On the other hand it's great when you're in the middle of a video and for some reason close it. So I'd say there's a few way to do it imho :
- Next to the play button you may have some kind of a "resume" button. That way the user has the option right on the main screen
- There's no preferences tab ATM but if there's plan of adding it in the future this could just be an on/off option.
- Asking to resume when opening the video doesn't seem too smooth but it's still a possibility.
- Lastly there could also be some kind of marker on the progress bar to indicate the position of the video when played last.

Just throwing ideas out there but I hope it may help you guys find the thing that suits you the most. Personally, I like the "resume button" and the "marker on progress bar" ideas. That's probably the less intrusive methods.

**Comment by furstenheim** [comment]
Maybe an option would be to only remember the position of the last video(s) you've seen or only for some time. If you open the last video you were watching, then it's almost certain you want to continue. If a year has passed, then you probably want to start again.
