### ISSUE TITLE
Create 32-bit Windows installer

### ISSUE THREAD

**Issue by feross** [feross/webtorrent-desktop#437]
I think a lot of the Windows install errors are caused by this.

Also, the Windows 32-bit marketshare is surprisingly large, still. This is the data that Steam collects (the best free data source I could find):

<img width="388" alt="screen shot 2016-04-22 at 19 28 49" src="https://cloud.githubusercontent.com/assets/121766/14758801/7681a462-08c0-11e6-890b-4dd999006473.png">

Windows 7 32bit: 6.97%
WIndows XP 32bit: 1.99%
Windows 10 32bit: 1.28%

So, all together that's 10% of Windows users.

From http://store.steampowered.com/hwsurvey/

**Comment by feross** [comment]
On second thought, I don't think is worth our time. It's unclear how we would manage the multiple `RELEASES` files generated by `electron-winstaller` for each architecture.

This 10% of Windows users is only going to continue decreasing over time, and we have plenty of growth opportunity among the other 90% of Windows users. By the time we make a bunch of those other 90% of users happy with WebTorrent Desktop, we can come back to this issue and maybe it won't be an issue anymore!

**Comment by feross** [comment]
It appears that the Atom team just ships a 32-bit binary to all Windows users.

https://github.com/atom/atom/issues/4881

I can't actually think of any downsides to doing that. We just need to test that the auto-updater can handle updating the 64-bit binaries to 32-bit without any issues.

Re-opening this issue to investigate since this solution would be super simple.

(Apparently, the Slack team does the same thing too, but for extra fanciness they set the Squirrel update URL to a 64-bit endpoint so the app updates itself to 64-bit on the second launch.)

**Comment by feross** [comment]
32-bit works fine on 64-bit and 32-bit Windows. I'll test the auto-updater from 64-bit 0.3.3 to 32-bit 0.4.0 just before the release.

@dcposch Does this sound reasonable to you?

**Comment by dcposch** [comment]
Yeah, that sounds reasonable.

The difference in efficiency should be pretty small according to [this](http://sfbay.craigslist.org/sfc/apa/5572463014.html). It can make a big difference for some CPU-intensive number crunching, but I don't think it will affect us much.

The only real limit is that the app won't be allowed to use more than 4GB of RAM. WebTorrent Desktop should never do that anyway. Let's ship it. Later, let's:
* Test what happens when we torrent many large files at the same time. 
* Find ways to shrink memory use, if we need to

**Comment by feross** [comment]
Sounds good.

**Comment by feross** [comment]
PR is merged!  https://github.com/feross/webtorrent-desktop/pull/509
