### ISSUE TITLE
Style Boost

### ISSUE THREAD

**Issue by Meadowcottage** [feross/webtorrent-desktop#514]
I've thought up a few ideas that would make WebTorrent a much slicker and functional app. Some of these features you may already be working on, but was not sure about, so I added in none the less to find out. Feedback if possible?

Player:
 - Loading bar color changeable in settings
 - Fast forward and reverse icons to left and right of center play button

Main Window:
 - Remove MenuBar and all menubar functions(Port to setting modal)
 - Centralize '+' button
 - Add settings icon & button to top right(current '+' button position)
 - Add settings modal page(including settings for: configs(player loading bar color, dark or light theme, download directory,etc)
 - Frameless window enabled(Replaced with custom close, minimize & maximize buttons)

Installer:
 - Loading image(gif with animated cycling border)
 - Choose installation directory

**Comment by feross** [comment]
Thanks for the suggestions!

> Loading bar color changeable in settings

Any reason? I've never seen a video player, even players with tons of options like VLC, with an option like this.

> Fast forward and reverse icons to left and right of center play button

Will consider it. I never use these buttons in video players, though.

> Remove MenuBar and all menubar functions(Port to setting modal)

Menu bars are pretty standard -- and even required on OS X. They're also really good for accessibility (for users with screen readers, or users who use the keyboard only).

> Centralize '+' button. Add settings icon & button to top right(current '+' button position)

Most users won't need to modify the settings. I'd prefer to add just a Preferences/Settings menu item to the menu bar. On OS X at least, settings appear in a standard menu item location.

> Add settings modal page(including settings for: configs(player loading bar color, dark or light theme, download directory,etc)

Yes, a preferences page is planned. See #62.

> Frameless window enabled(Replaced with custom close, minimize & maximize buttons)

Yes, this is planned, though there's no issue for it. The OS X app already has a frameless window. But it will require a bit more work for other OSs since we'll need to reimplement the close, minimize, and maximize buttons.

> Installer: Loading image(gif with animated cycling border)

Sure -- that would be cool.

> Choose installation directory

There's no way to offer this option using the Electron Windows installer generator. https://github.com/electron/windows-installer Unfortunately, this is the easiest way for us to generate a Windows installer right now since all Electron apps use it, and it's not worth trying to figure out something custom just to support a custom installation directory.

**Comment by Meadowcottage** [comment]
**Thanks for the fast reply.**

> Loading bar color changeable in settings

This was just an optional feature that I thought would maybe be nice to add at a later date as a nice customization feature for the player.

> Fast forward and reverse icons to left and right of center play button

Well the forward or previous buttons could either just fast forward time in the video or song or skip to the next video or song in the list.

> Remove MenuBar and all menubar functions(Port to setting modal)

> Centralize '+' button. Add settings icon & button to top right(current '+' button position)

> Add settings modal page(including settings for: configs(player loading bar color, dark or light theme, download directory,etc)

These 3 features were all sort of all meant to be one feature. Replace the, out of place, current menubar and all of the features with one setting button in the top right, where the current '+' button is and have that settings icon open a new modal window with all of the current menu bar options and features that are probably planned in #62 . But if you feel it would be better off for functionality reasons to keep the menu bar that seems perfectly reasonable.

> Frameless window enabled(Replaced with custom close, minimize & maximize buttons)

Frameless window was just another optional feature that would just make the overall look of the app a lot cleaner. If it cannot be done now or in the future it's not that big of a deal.

> Installer: Loading image(gif with animated cycling border)

I've already started work on an updated installing gif that has a pink/red border round in circles to have some sort of way to show that the installation is progressing.

> Choose installation directory

If the installation directory cannot be selected for where the app can be installed, would it at least be plausible to select the directory in which the torrent files are downloaded.

**Comment by feross** [comment]
> If the installation directory cannot be selected for where the app can be installed, would it at least be plausible to select the directory in which the torrent files are downloaded.

That is coming in a future release, soon.
