### ISSUE TITLE
App Sandbox Entitlements missing

### ISSUE THREAD

**Issue by pwnsdx** [feross/webtorrent-desktop#527]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)

Latest

**What operating system and version?**

OS X

**What did you do?**

Nothing.

**What did you expect to happen?**

App Sandboxing ( https://developer.apple.com/app-sandboxing/ )

App Sandbox Entitlement Keys : https://developer.apple.com/library/ios/documentation/Miscellaneous/Reference/EntitlementKeyReference/Chapters/EnablingAppSandbox.html#//apple_ref/doc/uid/TP40011195-CH4-SW1

**What actually happened?**

There is no App Sandboxing in Webtorrent Desktop

**Comment by feross** [comment]
This is a good and was already on my personal todo list. Sandboxing would limit the damage of a remote code execution vulnerability, and paves the way for App Store submission if we ever want to do that in the future.

@pwnsdx Is there any specific reason you need this right now? Otherwise, we'll get to this by v1.0.

Relevant:

- https://github.com/electron/electron/blob/master/docs/tutorial/mac-app-store-submission-guide.md
- https://developer.apple.com/library/ios/documentation/Miscellaneous/Reference/EntitlementKeyReference/Chapters/EnablingAppSandbox.html

**Comment by pwnsdx** [comment]
Hello,

> @pwnsdx Is there any specific reason you need this right now? Otherwise, we'll get to this by v1.0.

As it's a security feature that require minimal changes: the sooner, the better? ;)

**Comment by feross** [comment]
I just spent a few hours investigating this. Here's what I concluded.

It's non-trivial to sandbox an electron app that uses the auto-updater and crash reporter components because these don't work correctly when sandboxed. The auto updater needs to overwrite the application with a new version of itself, and the app can be anywhere on the filesystem.

When submitting electron apps to the mac app store, we can tell electron packager to omit these components (since the app store gives your app both of these features for free). `electron-packager` has a `mas` (mac app store) build target in addition to a `darwin` one.

But since we're shipping WebTorrent Desktop outside of the apps store, we need to keep these components -- particularly the auto-updater -- included in the app.

When we hit 1.0 we can try submitting a sandboxed version of WebTorrent Desktop to the app store. I'll keep the code around on a branch: https://github.com/feross/webtorrent-desktop/tree/entitlements

The unmerged commit: https://github.com/feross/webtorrent-desktop/commit/4b732f969923deb39ef8a8790e51267fbb09b5ab

But until we do an app store submission, this doesn't seem possible / worth the effort, much as I like the idea.

**Comment by pwnsdx** [comment]
Hello,

Thanks for the response. Sure, Sandboxing would disable auto-update but I use the 0.4.0 and I've seen no (automatic) update so far (the latest version is 0.6.1).

I can't wait the version 1.0 then!

Thanks,

**Comment by feross** [comment]
@pwnsdx We broke the auto-updater in v0.4.0. Please manually update to the latest version. Shouldn't happen again!

**Comment by pwnsdx** [comment]
Oh, I just did it, thanks so!
