### ISSUE TITLE
Crashes Cinnamon when opened (Arch  Linux)

### ISSUE THREAD

**Issue by abueide** [feross/webtorrent-desktop#532]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
Version 0.4.0 (0.93.3)
**What operating system and version?**
Arch Linux - Cinnamon DE - Downloaded using [AUR](https://aur.archlinux.org/packages/webtorrent-desktop-bin/) 
**Report**
When I opened webtorrent it crashed cinnamon into fallback mode, which asks to restart cinnamon. When cinnamon is restarted the program works as expected, until you attempt to launch it again.

**Comment by feross** [comment]
Do you have any further information, like a system crash log?

**Comment by abueide** [comment]
@feross  I did some research I can't find any place to look for cinnamon crash logs

**Comment by feross** [comment]
@abueide What command did you use to install webtorrent-desktop?

Do you get the same behavior if you run the official Linux binary?

Download it here: https://github.com/feross/webtorrent-desktop/releases/download/v0.5.1/WebTorrent-v0.5.1-linux-x64.zip

**Comment by abueide** [comment]
@feross Yes, the binary produces the same result. I used a program called packer (more common alternative is yaourt) to install the webtorrent desktop package from the AUR repository linked in op.

**Comment by feross** [comment]
There have been a lot of Electron crash fixes on Linux in recent releases of Electron. We upgraded to the latest Electron on `master`, so I'm curious if this is fixed for you now.

@abueide Care to give the code on `master` a chance?

```
git clone https://github.com/feross/webtorrent-desktop.git
cd webtorrent-desktop
npm install
npm start
```

**Comment by abueide** [comment]
@feross It didn't crash, should be resolved, thanks :)

**Comment by demoneaux** [comment]
Thanks for testing, we’ll close this issue for now. Feel free to report more issues if you encounter them!

**Comment by feross** [comment]
👍 👍 👍

**Comment by JethroTux** [comment]
Program crashes here using Archlinux+Cinnamon(latest) DE.
Aur package webtorrent-desktop-0.9.0-1 and even if cloning from git crash both.
Please help!
Cheerz.

**Comment by feross** [comment]
@JethroTux The package "webtorrent-desktop-0.9.0-1" you mentioned is not using the upgraded version of Electron, so it's not surprising that it crashed.

Strange that it crashed when using the code on `master`. Can you open a new issue and post a stack trace or any error messages you can find?

**Comment by JethroTux** [comment]
@feross I don't know what was wrong, but I made a fresh install and the application runs smoothly.
Perhaps it was crashing because it was using the old cached electron program version.
If it helps, I can paste some warning messages I got during the installation:

npm WARN deprecated lodash@1.2.1: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

npm WARN optional Skipping failed optional dependency //appdmg:
npm WARN notsup Not compatible with your operating system or architecture: appdmg@0.4.5
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
[giuseppe@Compaq64-ArchPc webtorrent-desktop]$ npm start

Thanks.

**Comment by feross** [comment]
@JethroTux Cool, glad it's working for you now. Those are normal npm warnings, nothing to worry about.
