### ISSUE TITLE
App does not start

### ISSUE THREAD

**Issue by tusharmath** [feross/webtorrent-desktop#556]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
Version 0.5.1 (0.93.4)

**What operating system and version?**
MAC OS 10.11.4

**What did you do?**
Simply started the app

**What did you expect to happen?**

**What actually happened?**

```error
ELECTRON_ASAR.js:109 Uncaught Error: ENOENT, static/file:/Users/tushar.mathur/Library/Application Support/WebTorrent/Posters/4b3dce31c713b02726f67e2ef49de9ff965ec3b7.jpg not found in /Applications/WebTorrent.app/Contents/Resources/app.asar
```

**Comment by feross** [comment]
@tusharmath How long ago did you install the app? Is there a chance that you installed a prior version and were auto-updated to this version?

It looks like there may be an issue with how we migrated the `torrentPath` config option, because "static/file:/Users/..." looks like an invalid URL.

If you don't mind losing your current app settings (downloaded files will not be affected), you can fix it like this:

1. Close WebTorrent Desktop
2. Open the Terminal app.
3. Paste the following command: `rm -rf ~/Library/Application\ Support/WebTorrent` and hit Enter.
4. Start WebTorrent Desktop.

**Comment by tusharmath** [comment]
Deleting the files solved the issue. Thanks!
