### ISSUE TITLE
Right click -> "Open in VLC"

### ISSUE THREAD

**Issue by feross** [feross/webtorrent-desktop#624]
Lots of people want to use VLC to always play their media. This feature would help out in situations where our player is too limited (like we don't currently handle multi-audio files due to Chrome limitations).

**Comment by NicolasPio** [comment]
I went open an issue about this. Would be interesting to let the VLC how default player.

**Comment by soofuzz** [comment]
or mpv player for the other platforms

https://github.com/mpv-player/mpv

**Comment by hshackle** [comment]
I can handle this. However, it seems like the current method of streaming with VLC assumes that webtorrent-desktop already began trying to stream it (since the only current usage of it is when it tries to stream a file and finds out it can't play it). Is there a cleaner way of approaching this other than letting webtorrent begin to stream the file and then immediately calling `dispatch('vlcPlay')` ?

**Comment by dcposch** [comment]
https://github.com/feross/webtorrent-desktop/pull/674

**Comment by mathiasvr** [comment]
Can this be closed now that we have the preference item, or do we want to be able to open specific files in an external player?

**Comment by feross** [comment]
@mathiasvr I think let's close this for now. We've made the situation A LOT better with the preference item.

The long term solution is to just improve our player so that 90% of users won't want to use an external player. There will always be the super nerds out there who want to set an external player (and the pref item is for them!)
