### ISSUE TITLE
Playback interruption upon new torrent open

### ISSUE THREAD

**Issue by janat08** [feross/webtorrent-desktop#643]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
0.7.2 (0.94.3)
**What operating system and version?**
Ubuntu 16.04
**What did you do?**
Open a torrent file during playback
**What did you expect to happen?**
Playback to continue
**What actually happened?**
Playback stopped

**Comment by feross** [comment]
Thanks, but this was an intentional UX decision. If you leave WebTorrent in the background, navigate to a torrent file, then open it, I think it's reasonable to stop playback and show the torrent list. This way, WebTorrent responds to what the user is currently doing.

If we just re-focused the WebTorrent window without stopping playback, it would be unclear if the torrent file was successfully added. WebTorrent remembers the position of last playback, so it shouldn't be too bad to just resume from the same spot.

Hope this makes sense.
