### ISSUE TITLE
pause a torrent

### ISSUE THREAD

**Issue by luisrudge** [feross/webtorrent-desktop#715]
Sometimes I want to prioritize a specific torrent. It'd be great to pause other torrents and resume them later. Today, I'm having to remove other torrents and add later again

**Comment by mathiasvr** [comment]
You can stop the torrent by clicking the blue button next to the red play button.

**Comment by luisrudge** [comment]
Holy cow.. Yeah, the tooltip says that. I'd never thought of it, though, because the icon is clearly not a "pause" button. It's more like a "download" button. Maybe we need to change that icon?

**Comment by dcposch** [comment]
@luisrudge I agree, the UI could be more clear

This is something we'll try to fix soon. I don't think we can make it a pause logo, because it would be confusing to have a pause button right next to the big red play button. Maybe it should turn into a pause logo on mouseover, though, to make it clear what clicking will do.

**Comment by dcposch** [comment]
In general I think the player screen is beautiful, but the torrent list (home screen) could use some love from a designer.
