### ISSUE TITLE
Uncaught Error: Cannot find module './pages/app'

### ISSUE THREAD

**Issue by anoadragon453** [feross/webtorrent-desktop#875]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
Version 0.13.1 (0.96.4) - b93f41f564d2838fa1354d94e55f99aede6cc068

**What operating system and version?**
Arch Linux x64

**What did you do?**
Seeded some low-peer torrents and restarted app.

**What did you expect to happen?**
See the list of torrents.

**What actually happened?**
![screenshot_2016-09-02_01-36-38](https://cloud.githubusercontent.com/assets/1342360/18200154/559c780c-70b8-11e6-8ec4-3ba4ae6b0712.png)
![screenshot_2016-09-02_01-36-39](https://cloud.githubusercontent.com/assets/1342360/18200262/ca137eb0-70b8-11e6-93a2-26eb6f2bf95e.png)

I was experiencing #854 so I updated to the latest commit in hopes to fix the issue, however I am presented with the same issue but with a new exception.

Here is my [config.json](https://gist.github.com/anoadragon453/1ac06d27ecaddb3d9ed9c0d4168336c6).

Thanks!

**Comment by mathiasvr** [comment]
Thanks for reporting, both errors should be fixed in the next release.

Right now you would have to remove all torrent entries with `"status": "new"` from your config.json.
For future reference I recommend that people do **not** post their config.json.

@dcposch We may want to release soon, to decrease #854 related errors.

**Comment by dcposch** [comment]
@mathiasvr sounds good, i'll try to ship an 0.14 release later today

**Comment by anoadragon453** [comment]
Just a heads up, without modifying my current config.json and on the latest commit 11f8e428a0ffcbafc7e598038b36c88fd26f0c22 I'm getting the following error:

`Uncaught Error: Cannot find module '../components/heading'`

**Comment by dcposch** [comment]
@anoadragon453 are you *sure* you're on that commit? I recommend quitting WebTorrent completely (make sure you don't have the installed app running), then starting again.

I thought that bug was fixed weeks ago.

Check your working directory. All files under `src/` should be all lowercase.

If you do have `src/renderer/components/Heading.js` (incorrectly uppercase), then try setting the following option:

```
git config --global core.ignorecase false
```

**Comment by anoadragon453** [comment]
I did a fresh install of the webtorrent-desktop-git AUR package which should grab the latest commit every time, but I'll do a manual got clone and build in a bit to make sure.
