### ISSUE TITLE
Allow toggle menu bar

### ISSUE THREAD

**Issue by anhskohbo** [feross/webtorrent-desktop#924]
**What operating system and version?**
Linux

**What did you expect to happen?**

Allow toggle menu bar like Slack app.

View -> Toggle Menu

**Comment by dcposch** [comment]
We only support Ubuntu with Unity, where the menu bar is always at the top of the screen, like on a Mac

CC @feross

**Comment by anhskohbo** [comment]
I'm used Gnome, look Webtorrent like dirty :) 
![screenshot from 2016-09-19 15-09-22](https://cloud.githubusercontent.com/assets/1529454/18625824/3eb76efa-7e7b-11e6-89b1-09f4ef114b15.png)

**Comment by dcposch** [comment]
Sorry, man. Desktop Linux is too fragmented.

For example, we had to fix a bug a few months ago where certain combinations of distro and window manager had a broke tray, so people would close the window, it would minimize to tray, and then they'd have no way to close the app because there was actually no tray.

**We already support a lot of platforms.**

MacOS is the easiest to work with. It's beautiful and not fragmented at all. Everyone is on 64-bit El Capitan or Sierra and everything just works. 💖

Then there's Windows, which comes in 32-bit and 64-bit and we try to support Win10, Windows 8.1, and Windows 7. Less fun to support, but that's where most of our users are.

Finally, we support recent 32- and 64-bit versions of Ubuntu with Unity.

**We can't go down the rabbit hole of supporting all the niche Linux setups.** Check out the family tree below. Ubuntu is one leaf on that tree. Even on Ubuntu, there's people running Unity, Gnome 2, Gnome 3, LXDE (Lubuntu), XFCE (Xubuntu). Life is too short for that.

If you use any Linux other than standard, out of the box Ubuntu with Unity, WebTorrent Desktop might still work (sweet!), but we won't add any extra features to support those configurations.

![](http://i.imgur.com/r8PKcEc.jpg)

**Comment by feross** [comment]
This issue is caused by Chromium using GTK2 instead of GTK3. Once they update to GTK3, then WebTorrent Desktop will get it via Electron. Related issue: https://github.com/electron/electron/issues/2927

P.S. @dcposch That is quite the chart. Here's a bigger version: http://futurist.se/gldt/wp-content/uploads/10.11/gldt1011.svg

**Comment by cra0zy** [comment]
Just support Ubuntu with Unity, GNOME and KDE, and with that you will have all your Linux bases covered.

**Comment by feross** [comment]
@cra0zy As mentioned before, once Chrome updates to GTK3, then WebTorrent will use a dark theme. I believe it should work on all systems, since we bundle GTK. But we can only officially support Ubuntu + Unity. Of course, PRs welcome to fix things for other variants.

**Comment by anhskohbo** [comment]
Electron have a option for `BrowserWindow` is `autoHideMenuBar`. Set is to `true` and you can toggle menu with Alt key.

I think good to add that.

**Comment by feross** [comment]
Thanks @anhskohbo, we'll consider that

**Comment by feross** [comment]
@anhskohbo See https://github.com/feross/webtorrent-desktop/issues/1134

**Comment by cra0zy** [comment]
Oh look, Ubuntu is dropping Unity and switching to GNOME...
