### ISSUE TITLE
Failed to connection to wss://tracker.btorrent.xyz/

### ISSUE THREAD

**Issue by henrypijames** [feross/webtorrent-desktop#943]
WTD 0.15.0 (0.96.5) on Windows 7 x64, all torrents remain at 0%, possibly because my ISP block well-known BT trackers, as well as many types of UDP connections (including some that are not related to BT).

The console logs nothing about failed tracker connections (would be nice to log those by default), but this:
> WebSocket connection to 'wss://tracker.btorrent.xyz/' failed: Error during WebSocket handshake: net::ERR_CONNECTION_RESET

Maybe WTD can add more ways to boottrap the initial connection to the swarm, for redundancy sake? WT is limited to WebSocket, but WTD is not, right?

**Comment by feross** [comment]
The "Failed to connection to wss://tracker.btorrent.xyz" message is not a fatal error. It just means that one attempt to contact this tracker has failed. This is likely because the tracker is down at the moment, or is overloaded with connections. (cc @DiegoRBaquero, who runs that tracker)

You can safely ignore this error. Unfortunately, there is no way to suppress a failed websocket connection error in the console as far as I can tell, or we would definitely do that.

WebTorrent Desktop uses all multiple peer finding mechanisms, including DHT, http/udp/websocket trackers, ut_pex peer exchange. This warning you're seeing is not the issue. If your ISP is blocking BitTorrent connections, trackers, or the DHT bootstrap nodes, then I'm afraid you're probably out of luck.

If other torrent clients also don't work for you, there's not much we can do here.

**Comment by DiegoRBaquero** [comment]
@henrypijames The BTorrent tracker restarts itself when memory consumption reaches certain limit. Nothing to worry about :)

**Comment by henrypijames** [comment]
I don't want less error messages in the console - I want more. Preferably, every failed connection should produce an error message.
